In [ ]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [ ]:
# read data
data <- read.csv('DENGBR23.csv')

In [ ]:
data %>% count(ID_AGRAVO)

  ID_AGRAVO n
1 A90       1517551

In [ ]:
data %>% dim

[1] 1517551     121

In [ ]:
# visualize data
data %>% head
data %>% colnames

  TP_NOT ID_AGRAVO DT_NOTIFIC SEM_NOT NU_ANO SG_UF_NOT ID_MUNICIP ID_REGIONA
1 2      A90       2023-02-28 202309  2023   33        330270     NA
2 2      A90       2023-04-27 202317  2023   33        330270     NA
3 2      A90       2023-11-10 202345  2023   33        330270     NA
4 2      A90       2023-12-09 202349  2023   33        330490     NA
5 2      A90       2023-07-03 202327  2023   33        330455     NA
6 2      A90       2023-11-28 202348  2023   33        330270     NA
  ID_UNIDADE DT_SIN_PRI ⋯ EVIDENCIA PLAQ_MENOR CON_FHD COMPLICA TP_SISTEMA
1 2266733    2023-02-20 ⋯ NA        NA         NA      NA       2
2 2266733    2023-04-23 ⋯ NA        NA         NA      NA       2
3 2266881    2023-11-05 ⋯ NA        NA         NA      NA       2
4 6369367    2023-12-05 ⋯ NA        NA         NA      NA       2
5 2269988    2023-06-15 ⋯ NA        NA         NA      NA       2
6 2266733    2023-11-27 ⋯ NA        NA         NA      NA       2
  NDUPLIC_N DT_DIGITA  CS_FLXRET FLXRECEBI MIGRADO_W
1 NA        2023-05-08 1         NA        NA
2 NA        2023-05-08 0         NA        NA
3 NA        2023-11-21 0         NA        NA
4 NA        2023-12-28 1         NA        NA
5 NA        2023-07-04 1         NA        NA
6 NA        2024-01-30 1         NA        NA

  [1] "TP_NOT"     "ID_AGRAVO"  "DT_NOTIFIC" "SEM_NOT"    "NU_ANO"
  [6] "SG_UF_NOT"  "ID_MUNICIP" "ID_REGIONA" "ID_UNIDADE" "DT_SIN_PRI"
 [11] "SEM_PRI"    "ANO_NASC"   "NU_IDADE_N" "CS_SEXO"    "CS_GESTANT"
 [16] "CS_RACA"    "CS_ESCOL_N" "SG_UF"      "ID_MN_RESI" "ID_RG_RESI"
 [21] "ID_PAIS"    "DT_INVEST"  "ID_OCUPA_N" "FEBRE"      "MIALGIA"
 [26] "CEFALEIA"   "EXANTEMA"   "VOMITO"     "NAUSEA"     "DOR_COSTAS"
 [31] "CONJUNTVIT" "ARTRITE"    "ARTRALGIA"  "PETEQUIA_N" "LEUCOPENIA"
 [36] "LACO"       "DOR_RETRO"  "DIABETES"   "HEMATOLOG"  "HEPATOPAT"
 [41] "RENAL"      "HIPERTENSA" "ACIDO_PEPT" "AUTO_IMUNE" "DT_CHIK_S1"
 [46] "DT_CHIK_S2" "DT_PRNT"    "RES_CHIKS1" "RES_CHIKS2" "RESUL_PRNT"
 [51] "DT_SORO"    "RESUL_SORO" "DT_NS1"     "RESUL_NS1"  "DT_VIRAL"
 [56] "RESUL_VI_N" "DT_PCR"     "RESUL_PCR_" "SOROTIPO"   "HISTOPA_N"
 [61] "IMUNOH_N"   "HOSPITALIZ" "DT_INTERNA" "UF"         "MUNICIPIO"
 [66] "TPAUTOCTO"  "COUFINF"    "COPAISINF"  "COMUNINF"   "CLASSI_FIN"
 [71] "CRITERIO"   "DOENCA_TRA" "CLINC_CHIK" "EVOLUCAO"   "DT_OBITO"
 [76] "DT_ENCERRA" "ALRM_HIPOT" "ALRM_PLAQ"  "ALRM_VOM"   "ALRM_SANG"
 [81] "ALRM_HEMAT" "ALRM_ABDOM" "ALRM_LETAR" "ALRM_HEPAT" "ALRM_LIQ"
 [86] "DT_ALRM"    "GRAV_PULSO" "GRAV_CONV"  "GRAV_ENCH"  "GRAV_INSUF"
 [91] "GRAV_TAQUI" "GRAV_EXTRE" "GRAV_HIPOT" "GRAV_HEMAT" "GRAV_MELEN"
 [96] "GRAV_METRO" "GRAV_SANG"  "GRAV_AST"   "GRAV_MIOC"  "GRAV_CONSC"
[101] "GRAV_ORGAO" "DT_GRAV"    "MANI_HEMOR" "EPISTAXE"   "GENGIVO"
[106] "METRO"      "PETEQUIAS"  "HEMATURA"   "SANGRAM"    "LACO_N"
[111] "PLASMATICO" "EVIDENCIA"  "PLAQ_MENOR" "CON_FHD"    "COMPLICA"
[116] "TP_SISTEMA" "NDUPLIC_N"  "DT_DIGITA"  "CS_FLXRET"  "FLXRECEBI"
[121] "MIGRADO_W"

In [ ]:
# remove information abount date and test (incomplete - black)
data %>% select(-c(DT_CHIK_S1:IMUNOH_N)) -> data

# remove information about place (keep only state)
data %>% select(-c(MUNICIPIO:COMUNINF)) -> data
data %>% select(-c(CRITERIO:CLINC_CHIK)) -> data

#remove several information, not needed (blank)
data %>% select(-c(TP_NOT:SEM_NOT)) -> data

# remove alarm since we are going to work with severe cases
data %>% select(-c(DT_ENCERRA:DT_ALRM)) -> data

In [ ]:
# filter only severe cases
data %>% count(CLASSI_FIN)

data %>% filter(CLASSI_FIN == 12) %>% count(EVOLUCAO)
data %>% filter(CLASSI_FIN == 12) -> data

# filter only cases of cure or death
data %>% filter(EVOLUCAO == 1  | EVOLUCAO == 2  | EVOLUCAO == 4 ) -> data
data %>% dim

  CLASSI_FIN n
1  1              18
2  8          223458
3 10         1267457
4 11           19954
5 12            1538
6 NA            5126

  EVOLUCAO n
1  1       635
2  2       684
3  3        41
4  4        29
5  9        47
6 NA       102

[1] 1348   81

In [ ]:
# change evolucao to binary
data %>% mutate(death = if_else(EVOLUCAO == 1, 0, 1)) -> data
data %>% count(death)

  death n
1 0     635
2 1     713

In [ ]:
data %>% colnames

 [1] "NU_ANO"     "SG_UF_NOT"  "ID_MUNICIP" "ID_REGIONA" "ID_UNIDADE"
 [6] "DT_SIN_PRI" "SEM_PRI"    "ANO_NASC"   "NU_IDADE_N" "CS_SEXO"
[11] "CS_GESTANT" "CS_RACA"    "CS_ESCOL_N" "SG_UF"      "ID_MN_RESI"
[16] "ID_RG_RESI" "ID_PAIS"    "DT_INVEST"  "ID_OCUPA_N" "FEBRE"
[21] "MIALGIA"    "CEFALEIA"   "EXANTEMA"   "VOMITO"     "NAUSEA"
[26] "DOR_COSTAS" "CONJUNTVIT" "ARTRITE"    "ARTRALGIA"  "PETEQUIA_N"
[31] "LEUCOPENIA" "LACO"       "DOR_RETRO"  "DIABETES"   "HEMATOLOG"
[36] "HEPATOPAT"  "RENAL"      "HIPERTENSA" "ACIDO_PEPT" "AUTO_IMUNE"
[41] "HOSPITALIZ" "DT_INTERNA" "UF"         "CLASSI_FIN" "EVOLUCAO"
[46] "DT_OBITO"   "GRAV_PULSO" "GRAV_CONV"  "GRAV_ENCH"  "GRAV_INSUF"
[51] "GRAV_TAQUI" "GRAV_EXTRE" "GRAV_HIPOT" "GRAV_HEMAT" "GRAV_MELEN"
[56] "GRAV_METRO" "GRAV_SANG"  "GRAV_AST"   "GRAV_MIOC"  "GRAV_CONSC"
[61] "GRAV_ORGAO" "DT_GRAV"    "MANI_HEMOR" "EPISTAXE"   "GENGIVO"
[66] "METRO"      "PETEQUIAS"  "HEMATURA"   "SANGRAM"    "LACO_N"
[71] "PLASMATICO" "EVIDENCIA"  "PLAQ_MENOR" "CON_FHD"    "COMPLICA"
[76] "TP_SISTEMA" "NDUPLIC_N"  "DT_DIGITA"  "CS_FLXRET"  "FLXRECEBI"
[81] "MIGRADO_W"  "death"

In [ ]:
# inspecting data distribution according to state
data %>% count(SG_UF_NOT)

   SG_UF_NOT n
1  11          7
2  12          2
3  13         12
4  15          3
5  17          3
6  21         11
7  22         11
8  23         20
9  24          6
10 25          3
11 26          4
12 27          4
13 28         16
14 29         70
15 31        262
16 33         68
17 35        376
18 41        169
19 42        118
20 43         31
21 50         38
22 51         19
23 52         74
24 53         21

In [ ]:
data %>% unique %>% dim

[1] 1348   82

In [ ]:
# inspecting data distribution according year of birth
data %>% count(ANO_NASC)

# remove patients without this information
data %>% filter(!is.na(ANO_NASC)) -> data

# create a new column with age
data %>% mutate(age = 2023 - ANO_NASC) %>% count(age) %>% slice(1:15)
data %>% mutate(age = 2023 - ANO_NASC) %>% count(age) %>% tail(12)
data %>% mutate(age = 2023 - ANO_NASC) -> data

    ANO_NASC n
1   1922      1
2   1923      2
3   1924      4
4   1926      1
5   1927      2
6   1928      2
7   1929      9
8   1930      8
9   1931      5
10  1932      9
11  1933     10
12  1934     15
13  1935     13
14  1936     22
15  1937     16
16  1938     15
17  1939     14
18  1940     23
19  1941     17
20  1942     15
21  1943     18
22  1944     18
23  1945     12
24  1946     20
25  1947     13
26  1948     21
27  1949     21
28  1950     17
29  1951     20
30  1952     16
⋮   ⋮        ⋮
73  1995     18
74  1996     11
75  1997     14
76  1998     12
77  1999     12
78  2000      8
79  2001     20
80  2002     17
81  2003      8
82  2004     12
83  2005     18
84  2006     12
85  2007     14
86  2008      9
87  2009     14
88  2010     11
89  2011     12
90  2012     14
91  2013      6
92  2014     14
93  2015      5
94  2016      7
95  2017      9
96  2018     12
97  2019      9
98  2020      7
99  2021      6
100 2022     19
101 2023      9
102   NA      1

   age n
1   0   9
2   1  19
3   2   6
4   3   7
5   4   9
6   5  12
7   6   9
8   7   7
9   8   5
10  9  14
11 10   6
12 11  14
13 12  12
14 13  11
15 14  14

    age n
90   89 15
91   90 10
92   91  9
93   92  5
94   93  8
95   94  9
96   95  2
97   96  2
98   97  1
99   99  4
100 100  2
101 101  1

In [ ]:
# remove patients younger than 12 years old
data %>% filter(age > 11) -> data

In [ ]:
data %>% count(CS_SEXO)

# create a new column with numeric values
data %>% filter(CS_SEXO != 'I') -> data
data %>% count(CS_SEXO)

data %>% mutate(sex = if_else(CS_SEXO == 'M', 0, 1)) -> data
data %>% count(sex)

# remove the former column
data %>% select(-CS_SEXO) -> data

  CS_SEXO n
1 F       657
2 I         3
3 M       570

  CS_SEXO n
1 F       657
2 M       570

  sex n
1 0   570
2 1   657

In [ ]:
# check the column pregnancy
data %>% count(CS_GESTANT)

  CS_GESTANT n
1 1            2
2 2            2
3 3            8
4 4            5
5 5          492
6 6          682
7 9           36

In [ ]:
#check for duplicates
data %>% dim
data %>% unique %>% dim

[1] 1227   83

[1] 1227   83

In [ ]:
# transform the column pregnant in binary, orignally diferent values refer to difernt stages on pregnancy

data %>% mutate(pregnant = if_else((CS_GESTANT == 1 |
                               CS_GESTANT == 2 |
                               CS_GESTANT == 3 |
                               CS_GESTANT == 4), 1, 0)) %>% count(pregnant)


data %>% mutate(pregnant = if_else((CS_GESTANT == 1 |
                               CS_GESTANT == 2 |
                               CS_GESTANT == 3 |
                               CS_GESTANT == 4), 1, 0)) -> data

data %>% select(-CS_GESTANT) -> data

  pregnant n
1 0        1210
2 1          17

In [ ]:
# remove unknown race, or na values
data %>% count(CS_RACA)

# white
data %>% mutate(white = if_else(CS_RACA == 1, 1, 0)) -> data
data %>% count(white)

# black
data %>% mutate(black = if_else(CS_RACA == 2, 1, 0)) -> data
data %>% count(black)

# parda
data %>% mutate(parda = if_else(CS_RACA == 4, 1, 0)) -> data
data %>% count(parda)

  CS_RACA n
1 1       697
2 2        41
3 3        17
4 4       355
5 5         5
6 9       112

  white n
1 0     530
2 1     697

  black n
1 0     1186
2 1       41

  parda n
1 0     872
2 1     355

In [ ]:
# how many groups by age, race, city and sex
data %>% group_by(age, CS_RACA, ID_MN_RESI, sex) %>% n_groups

[1] 1187

In [ ]:
# check year of schooling. 9 = unknown.
data %>% count(CS_ESCOL_N)

   CS_ESCOL_N n
1   0          26
2   1          65
3   2          43
4   3         121
5   4          70
6   5          47
7   6         195
8   7          12
9   8          69
10  9         414
11 NA         165

In [ ]:
# how many groups by age, race, city and sex
data %>% group_by(age, CS_RACA, ID_MN_RESI, sex) %>% n_groups

# create a new column with the average
data %>% group_by(age, CS_RACA, ID_MN_RESI, sex) %>% mutate(average = mean(CS_ESCOL_N, na.rm=TRUE)) %>%
    ungroup -> data

# when CS_ESCOL_N is na or 9 change by the average
data %>% mutate(CS_ESCOL_N = if_else((is.na(CS_ESCOL_N)), round(average), CS_ESCOL_N)) %>% count(CS_ESCOL_N)
data %>% mutate(CS_ESCOL_N = if_else((is.na(CS_ESCOL_N)), round(average), CS_ESCOL_N)) -> data
data %>% select(-average) -> data

# if is still NA consider groups of age, race and sex

# create a new column with the average
data %>% group_by(age, CS_RACA, sex) %>% mutate(average = mean(CS_ESCOL_N, na.rm=TRUE)) %>%
    ungroup -> data

# when CS_ESCOL_N is na change by the average
data %>% mutate(CS_ESCOL_N = if_else((is.na(CS_ESCOL_N)), round(average), CS_ESCOL_N)) %>% count(CS_ESCOL_N)
data %>% mutate(CS_ESCOL_N = if_else((is.na(CS_ESCOL_N)), round(average), CS_ESCOL_N)) -> data
data %>% select(-average) -> data

[1] 1187

   CS_ESCOL_N n
1    0         26
2    1         65
3    2         44
4    3        121
5    4         70
6    5         48
7    6        197
8    7         12
9    8         70
10   9        420
11 NaN        154

   CS_ESCOL_N n
1    0         26
2    1         68
3    2         50
4    3        122
5    4         88
6    5         64
7    6        223
8    7         24
9    8         82
10   9        449
11 NaN         31

In [ ]:
# if is still na, drop it
data %>% count(CS_ESCOL_N)

data %>% filter(!(is.na(CS_ESCOL_N))) -> data

data %>% count(HOSPITALIZ)

data %>% dim

   CS_ESCOL_N n
1    0         26
2    1         68
3    2         50
4    3        122
5    4         88
6    5         64
7    6        223
8    7         24
9    8         82
10   9        449
11 NaN         31

  HOSPITALIZ n
1  1         1040
2  2          113
3  9           14
4 NA           29

[1] 1196   86

In [ ]:
data %>% colnames

 [1] "NU_ANO"     "SG_UF_NOT"  "ID_MUNICIP" "ID_REGIONA" "ID_UNIDADE"
 [6] "DT_SIN_PRI" "SEM_PRI"    "ANO_NASC"   "NU_IDADE_N" "CS_RACA"
[11] "CS_ESCOL_N" "SG_UF"      "ID_MN_RESI" "ID_RG_RESI" "ID_PAIS"
[16] "DT_INVEST"  "ID_OCUPA_N" "FEBRE"      "MIALGIA"    "CEFALEIA"
[21] "EXANTEMA"   "VOMITO"     "NAUSEA"     "DOR_COSTAS" "CONJUNTVIT"
[26] "ARTRITE"    "ARTRALGIA"  "PETEQUIA_N" "LEUCOPENIA" "LACO"
[31] "DOR_RETRO"  "DIABETES"   "HEMATOLOG"  "HEPATOPAT"  "RENAL"
[36] "HIPERTENSA" "ACIDO_PEPT" "AUTO_IMUNE" "HOSPITALIZ" "DT_INTERNA"
[41] "UF"         "CLASSI_FIN" "EVOLUCAO"   "DT_OBITO"   "GRAV_PULSO"
[46] "GRAV_CONV"  "GRAV_ENCH"  "GRAV_INSUF" "GRAV_TAQUI" "GRAV_EXTRE"
[51] "GRAV_HIPOT" "GRAV_HEMAT" "GRAV_MELEN" "GRAV_METRO" "GRAV_SANG"
[56] "GRAV_AST"   "GRAV_MIOC"  "GRAV_CONSC" "GRAV_ORGAO" "DT_GRAV"
[61] "MANI_HEMOR" "EPISTAXE"   "GENGIVO"    "METRO"      "PETEQUIAS"
[66] "HEMATURA"   "SANGRAM"    "LACO_N"     "PLASMATICO" "EVIDENCIA"
[71] "PLAQ_MENOR" "CON_FHD"    "COMPLICA"   "TP_SISTEMA" "NDUPLIC_N"
[76] "DT_DIGITA"  "CS_FLXRET"  "FLXRECEBI"  "MIGRADO_W"  "death"
[81] "age"        "sex"        "pregnant"   "white"      "black"
[86] "parda"

In [ ]:
data %>% count(SEM_PRI)
data %>% mutate(week = SEM_PRI - 202300) -> data

   SEM_PRI n
1  202301  11
2  202302  14
3  202303  15
4  202304  14
5  202305  26
6  202306  34
7  202307  32
8  202308  37
9  202309  40
10 202310  44
11 202311  42
12 202312  65
13 202313  58
14 202314  85
15 202315  92
16 202316  80
17 202317  49
18 202318  57
19 202319  42
20 202320  58
21 202321  27
22 202322  29
23 202323  24
24 202324  19
25 202325  13
26 202326  12
27 202327   8
28 202328  17
29 202329   6
30 202330   8
31 202331   9
32 202332   3
33 202333   9
34 202334   5
35 202335   3
36 202336   5
37 202337   2
38 202338   3
39 202339   5
40 202340   3
41 202341   2
42 202342   4
43 202343   9
44 202344   5
45 202345   6
46 202346   8
47 202347   7
48 202348   4
49 202349  20
50 202350   7
51 202351  11
52 202352   8

In [ ]:
data$dt_severity <- as.Date(data$DT_GRAV)
data$dt_death <- as.Date(data$DT_OBITO)

data %>% mutate(days = difftime(dt_death, dt_severity, units = 'days')) -> data

data$days <- as.numeric(data$days)

data %>% count(days)

data %>% filter(is.na(days) | days < 41) -> data

   days  n
1  -1095   1
2   -366   1
3   -117   1
4    -73   1
5    -59   1
6    -31   1
7    -29   1
8    -26   1
9    -22   1
10   -19   1
11   -15   1
12   -12   1
13    -2   2
14    -1   1
15     0 165
16     1 144
17     2  64
18     3  38
19     4  21
20     5  23
21     6  23
22     7  25
23     8  20
24     9  14
25    10  13
26    11   9
27    12  10
28    13  11
29    14   6
30    15   7
31    16   6
32    17   2
33    18   3
34    19   4
35    21   4
36    23   1
37    24   3
38    25   2
39    26   2
40    27   1
41    28   2
42    29   1
43    30   1
44    31   1
45    32   2
46    33   1
47    36   2
48    38   1
49    44   2
50    45   1
51    52   1
52    54   1
53    57   1
54    61   1
55    65   1
56    76   1
57    88   1
58   122   1
59   366   1
60    NA 537

In [ ]:
data %>% filter (days < 0) %>% select(dt_death, dt_severity)

   dt_death   dt_severity
1  2023-04-08 2023-04-27
2  2023-02-27 2023-03-21
3  2023-03-14 2023-04-14
4  2023-05-10 2023-05-25
5  2023-01-26 2026-01-25
6  2023-04-30 2023-05-12
7  2023-05-19 2023-05-20
8  2023-08-05 2023-08-31
9  2023-03-26 2023-03-28
10 2023-05-12 2023-07-10
11 2023-05-15 2023-07-27
12 2023-01-22 2023-02-20
13 2023-01-11 2023-05-08
14 2023-03-19 2023-03-21
15 2023-12-28 2024-12-28

In [ ]:
data %>% colnames

 [1] "NU_ANO"      "SG_UF_NOT"   "ID_MUNICIP"  "ID_REGIONA"  "ID_UNIDADE"
 [6] "DT_SIN_PRI"  "SEM_PRI"     "ANO_NASC"    "NU_IDADE_N"  "CS_RACA"
[11] "CS_ESCOL_N"  "SG_UF"       "ID_MN_RESI"  "ID_RG_RESI"  "ID_PAIS"
[16] "DT_INVEST"   "ID_OCUPA_N"  "FEBRE"       "MIALGIA"     "CEFALEIA"
[21] "EXANTEMA"    "VOMITO"      "NAUSEA"      "DOR_COSTAS"  "CONJUNTVIT"
[26] "ARTRITE"     "ARTRALGIA"   "PETEQUIA_N"  "LEUCOPENIA"  "LACO"
[31] "DOR_RETRO"   "DIABETES"    "HEMATOLOG"   "HEPATOPAT"   "RENAL"
[36] "HIPERTENSA"  "ACIDO_PEPT"  "AUTO_IMUNE"  "HOSPITALIZ"  "DT_INTERNA"
[41] "UF"          "CLASSI_FIN"  "EVOLUCAO"    "DT_OBITO"    "GRAV_PULSO"
[46] "GRAV_CONV"   "GRAV_ENCH"   "GRAV_INSUF"  "GRAV_TAQUI"  "GRAV_EXTRE"
[51] "GRAV_HIPOT"  "GRAV_HEMAT"  "GRAV_MELEN"  "GRAV_METRO"  "GRAV_SANG"
[56] "GRAV_AST"    "GRAV_MIOC"   "GRAV_CONSC"  "GRAV_ORGAO"  "DT_GRAV"
[61] "MANI_HEMOR"  "EPISTAXE"    "GENGIVO"     "METRO"       "PETEQUIAS"
[66] "HEMATURA"    "SANGRAM"     "LACO_N"      "PLASMATICO"  "EVIDENCIA"
[71] "PLAQ_MENOR"  "CON_FHD"     "COMPLICA"    "TP_SISTEMA"  "NDUPLIC_N"
[76] "DT_DIGITA"   "CS_FLXRET"   "FLXRECEBI"   "MIGRADO_W"   "death"
[81] "age"         "sex"         "pregnant"    "white"       "black"
[86] "parda"       "week"        "dt_severity" "dt_death"    "days"

In [ ]:
data %>% select(-c(NU_ANO, ID_MUNICIP:CS_RACA, SG_UF:ID_OCUPA_N, HOSPITALIZ, DT_OBITO, MANI_HEMOR:MIGRADO_W,
                   DT_INTERNA:EVOLUCAO, dt_severity, dt_death, DT_GRAV, DT_OBITO)) -> data

In [ ]:
data %>% dim

[1] 1184   47

In [ ]:
data %>% count(SG_UF_NOT)

   SG_UF_NOT n
1  11          6
2  12          2
3  13         12
4  15          2
5  17          3
6  21         11
7  22          8
8  23         16
9  24          3
10 25          3
11 26          3
12 27          4
13 28         12
14 29         57
15 31        239
16 33         53
17 35        334
18 41        153
19 42        111
20 43         28
21 50         28
22 51         14
23 52         67
24 53         15

In [ ]:
# south
data %>% mutate(south = if_else((SG_UF_NOT >= 41  & SG_UF_NOT <= 43), 1, 0)) -> data
data %>% count(south)

# south_e
data %>% mutate(south_e = if_else((SG_UF_NOT >= 31  & SG_UF_NOT <= 35), 1, 0)) -> data
data %>% count(south_e)


# north
data %>% mutate(north = if_else((SG_UF_NOT < 18), 1, 0)) -> data
data %>% count(north)

# north_e
data %>% mutate(north_e = if_else((SG_UF_NOT >= 20  & SG_UF_NOT <= 30), 1, 0)) -> data
data %>% count(north_e)

# center_w
data %>% mutate(center_w = if_else((SG_UF_NOT > 49), 1, 0)) -> data
data %>% count(center_w)

data %>% select(-c(SG_UF_NOT)) -> data

  south n
1 0     892
2 1     292

  south_e n
1 0       558
2 1       626

  north n
1 0     1159
2 1       25

  north_e n
1 0       1067
2 1        117

  center_w n
1 0        1060
2 1         124

In [ ]:
data %>% colnames

 [1] "CS_ESCOL_N" "FEBRE"      "MIALGIA"    "CEFALEIA"   "EXANTEMA"
 [6] "VOMITO"     "NAUSEA"     "DOR_COSTAS" "CONJUNTVIT" "ARTRITE"
[11] "ARTRALGIA"  "PETEQUIA_N" "LEUCOPENIA" "LACO"       "DOR_RETRO"
[16] "DIABETES"   "HEMATOLOG"  "HEPATOPAT"  "RENAL"      "HIPERTENSA"
[21] "ACIDO_PEPT" "AUTO_IMUNE" "GRAV_PULSO" "GRAV_CONV"  "GRAV_ENCH"
[26] "GRAV_INSUF" "GRAV_TAQUI" "GRAV_EXTRE" "GRAV_HIPOT" "GRAV_HEMAT"
[31] "GRAV_MELEN" "GRAV_METRO" "GRAV_SANG"  "GRAV_AST"   "GRAV_MIOC"
[36] "GRAV_CONSC" "GRAV_ORGAO" "death"      "age"        "sex"
[41] "pregnant"   "white"      "black"      "parda"      "week"
[46] "days"       "south"      "south_e"    "north"      "north_e"
[51] "center_w"

In [ ]:
data %>% select(-days) -> data

In [ ]:
# the value 2 means the non-occurrence of a symptom, change this to 0
data %>% select(FEBRE:GRAV_ORGAO) -> symptoms
data %>% select(!(FEBRE:GRAV_ORGAO)) -> others

symptoms %>% head

symptoms <- symptoms %>%
  mutate_all(~ ifelse(. == 2, 0, .))

symptoms %>% head

symptoms %>% cbind(others) -> data

  FEBRE MIALGIA CEFALEIA EXANTEMA VOMITO NAUSEA DOR_COSTAS CONJUNTVIT ARTRITE
1 2     1       2        2        2      2      2          2          2
2 1     1       1        2        2      1      2          2          2
3 1     2       1        2        1      1      2          2          2
4 1     1       1        1        1      1      1          2          2
5 1     1       1        2        2      2      2          2          2
6 1     2       1        2        1      1      2          2          2
  ARTRALGIA ⋯ GRAV_EXTRE GRAV_HIPOT GRAV_HEMAT GRAV_MELEN GRAV_METRO GRAV_SANG
1 1         ⋯ 2          2          2          2          2          2
2 2         ⋯ 2          2          1          2          2          2
3 2         ⋯ 2          2          2          2          2          2
4 2         ⋯ 1          2          2          2          2          2
5 2         ⋯ 1          2          2          2          2          2
6 2         ⋯ 2          2          2          2          2          2
  GRAV_AST GRAV_MIOC GRAV_CONSC GRAV_ORGAO
1 2        2         2          1
2 2        2         2          2
3 2        2         2          1
4 2        2         2          2
5 2        2         2          2
6 2        2         2          2

  FEBRE MIALGIA CEFALEIA EXANTEMA VOMITO NAUSEA DOR_COSTAS CONJUNTVIT ARTRITE
1 0     1       0        0        0      0      0          0          0
2 1     1       1        0        0      1      0          0          0
3 1     0       1        0        1      1      0          0          0
4 1     1       1        1        1      1      1          0          0
5 1     1       1        0        0      0      0          0          0
6 1     0       1        0        1      1      0          0          0
  ARTRALGIA ⋯ GRAV_EXTRE GRAV_HIPOT GRAV_HEMAT GRAV_MELEN GRAV_METRO GRAV_SANG
1 1         ⋯ 0          0          0          0          0          0
2 0         ⋯ 0          0          1          0          0          0
3 0         ⋯ 0          0          0          0          0          0
4 0         ⋯ 1          0          0          0          0          0
5 0         ⋯ 1          0          0          0          0          0
6 0         ⋯ 0          0          0          0          0          0
  GRAV_AST GRAV_MIOC GRAV_CONSC GRAV_ORGAO
1 0        0         0          1
2 0        0         0          0
3 0        0         0          1
4 0        0         0          0
5 0        0         0          0
6 0        0         0          0

In [ ]:
data %>% colnames
data %>% dim
sum(is.na(data))

 [1] "FEBRE"      "MIALGIA"    "CEFALEIA"   "EXANTEMA"   "VOMITO"
 [6] "NAUSEA"     "DOR_COSTAS" "CONJUNTVIT" "ARTRITE"    "ARTRALGIA"
[11] "PETEQUIA_N" "LEUCOPENIA" "LACO"       "DOR_RETRO"  "DIABETES"
[16] "HEMATOLOG"  "HEPATOPAT"  "RENAL"      "HIPERTENSA" "ACIDO_PEPT"
[21] "AUTO_IMUNE" "GRAV_PULSO" "GRAV_CONV"  "GRAV_ENCH"  "GRAV_INSUF"
[26] "GRAV_TAQUI" "GRAV_EXTRE" "GRAV_HIPOT" "GRAV_HEMAT" "GRAV_MELEN"
[31] "GRAV_METRO" "GRAV_SANG"  "GRAV_AST"   "GRAV_MIOC"  "GRAV_CONSC"
[36] "GRAV_ORGAO" "CS_ESCOL_N" "death"      "age"        "sex"
[41] "pregnant"   "white"      "black"      "parda"      "week"
[46] "south"      "south_e"    "north"      "north_e"    "center_w"

[1] 1184   50

[1] 75

In [ ]:
data <- na.omit(data)

In [ ]:
data %>% count(death)
data %>% dim

  death n
1 0     532
2 1     647

[1] 1179   50

In [ ]:
colSums(data, na.rm = TRUE)
data %>% select(-c(ACIDO_PEPT)) -> data

     FEBRE    MIALGIA   CEFALEIA   EXANTEMA     VOMITO     NAUSEA DOR_COSTAS
       929        881        702        158        504        562        273
CONJUNTVIT    ARTRITE  ARTRALGIA PETEQUIA_N LEUCOPENIA       LACO  DOR_RETRO
        37         80        251        184        262         57        286
  DIABETES  HEMATOLOG  HEPATOPAT      RENAL HIPERTENSA ACIDO_PEPT AUTO_IMUNE
       254         33         26         65        456          8         32
GRAV_PULSO  GRAV_CONV  GRAV_ENCH GRAV_INSUF GRAV_TAQUI GRAV_EXTRE GRAV_HIPOT
       284        165        196        271        409        442        335
GRAV_HEMAT GRAV_MELEN GRAV_METRO  GRAV_SANG   GRAV_AST  GRAV_MIOC GRAV_CONSC
       194        161         64         48         61         34        448
GRAV_ORGAO CS_ESCOL_N      death        age        sex   pregnant      white
       190       7299        647      64336        634         17        683
     black      parda       week      south    south_e      north    north_e
        37        345      20893        292        626         25        117
  center_w
       119

In [ ]:
data %>% select(FEBRE:CS_ESCOL_N, age:center_w, death) -> data

In [ ]:
data %>% colnames

 [1] "FEBRE"      "MIALGIA"    "CEFALEIA"   "EXANTEMA"   "VOMITO"
 [6] "NAUSEA"     "DOR_COSTAS" "CONJUNTVIT" "ARTRITE"    "ARTRALGIA"
[11] "PETEQUIA_N" "LEUCOPENIA" "LACO"       "DOR_RETRO"  "DIABETES"
[16] "HEMATOLOG"  "HEPATOPAT"  "RENAL"      "HIPERTENSA" "AUTO_IMUNE"
[21] "GRAV_PULSO" "GRAV_CONV"  "GRAV_ENCH"  "GRAV_INSUF" "GRAV_TAQUI"
[26] "GRAV_EXTRE" "GRAV_HIPOT" "GRAV_HEMAT" "GRAV_MELEN" "GRAV_METRO"
[31] "GRAV_SANG"  "GRAV_AST"   "GRAV_MIOC"  "GRAV_CONSC" "GRAV_ORGAO"
[36] "CS_ESCOL_N" "age"        "sex"        "pregnant"   "white"
[41] "black"      "parda"      "week"       "south"      "south_e"
[46] "north"      "north_e"    "center_w"   "death"

In [ ]:
colnames(data) <- c("fever", "myalgia", "headache",
                  "rash", "vomiting", "nausea",
                  "back_pain", "conjunctivitis", "arthritis",
                  "arthralgia", "petechiae_n", "leukopenia",
                  "lace", "retroorbital_pain", "diabetes",
                  "hematological_diseases", "hepatopathy", "chronic_kidney_disease",
                  "hypertension", "autoimmune_disease", "weak_pulse",
                  "convergent_pressure", "capillary_time", "fluid_accumulation",
                  "tachycardia", "cold_extremities", "hypotension",
                  "hematemesis", "melena", "metrorrhagia",
                  "cns_bleeding", "AST/ALT_ratio", "myocarditis",
                  "consciousness", "other_organs", "education", "age",
                  "sex", "pregnant", "white",
                  "black", "parda", "week",
                  "south", "southeast", "north",
                  "northeast", "central_west", "death")

In [ ]:
data %>% select(-c(fever: retroorbital_pain)) -> data

In [ ]:
#data %>% select(-c(fever: retroorbital_pain)) -> data
data %>% write_csv('death_dengue_23.csv')